### ISSUE TITLE
Does not work on Internet Explorer

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/card#10]
At all apparently.

**Comment by DalaiLlaama** [comment]
I just tried this using daicard.io/rinkeby, and it seems to be working pretty well. The symptoms I noticed at first are not exhibited.

**Comment by ArjunBhuptani** [comment]
oh nice! Thanks for giving it a try @DalaiLlaama. I think the changes to how we auth might have fixed it. Going to close this for now and add IE testing to our releaseflow.
