### ISSUE TITLE
Collateral Data Pipeline

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/card#12]
We need a good way to collect data on channel collateralization and payment behavior so that we can build a more efficient collateral algo.

Initially, this can just be a .env private key linked portal for team to get raw collateral data from the DB and contract?

Open to any way to implement this so long as it's fast and simple.

**Comment by LayneHaber** [comment]
I would suggest we make chainsaw poll the collateral available information from the contract as it polls contract events, that way we can run it all with SQL queries in postico for now, and build a UI on it later. would be best to do this in a way where web3 is not involved if its a data pipeline thing

**Comment by ArjunBhuptani** [comment]
Sounds good! We also need the ability to query DB.

I think the main part of this is just making sure only we can get DB info (for now) and making sure that it's simple enough to do multiple times a day as a habit

**Comment by hthillman** [comment]
MVP done and deployed, pending one minor bugfix (#117)
