### ISSUE TITLE
[Hard to Reproduce] QR Scanner bugs

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/card#13]
Sometimes, and with some browsers, the QR scanner can fail to open properly.

Creating this issue so we can reference it later if we see it pop up for more users.

**Comment by LayneHaber** [comment]
So, I've had issues with scanning QR codes from my mobile device. Not sure if this belongs here, but curious if others have seen this issue as well

**Comment by LayneHaber** [comment]
iOS issues on chrome, also some issues on Brave with prompting. Punting for this release
