### ISSUE TITLE
Recovering from Mnemonic into Metamask gives a different address

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/card#14]
Yesterday, a user accidentally deposited mainnet Dai into their Card. When they recovered the rinkeby mnemonic into their metamask, they received a different output address than that of the browser wallet.

Can we please figure out what's supposed to happen here? If users are not able to recover funds from mnemonic, this is a big issue.

Will probably require a bit of testing.

**Comment by LayneHaber** [comment]
Not that it's a reliable source, but this seems to be an issue with our implementation according to [this](https://www.reddit.com/r/ethereum/comments/7u1xdb/accidentally_sent_1_real_ether_to_test_network/) reddit thread.

Doing some light local testing, (pro-tip, new google account = new metamask) and I can recover on local and rinkeby, but recovering with the seed phrase on metamask led to a different account. Could be related to [this restore from seed quirk](https://metamask.zendesk.com/hc/en-us/articles/360015289612-Restoring-MetaMask-from-seed-phrase) issues where the account restored is not the first one created? Not sure exactly, but seems it may be the issue. Was able to import the wallet on the card (couldnt try mainnet), but continually get the wrong address on metamask when I recover there.

**Comment by snario** [comment]
Looks like a path issue? If you replace

https://github.com/ConnextProject/card/blob/bc6965cec33a5855180a1cd11caf3fb0b9fb4235/src/walletGen.js#L9

with

```ts
const wallet = await hdkey
    .fromMasterSeed(mnemonic)
    .derivePath("m/44'/60'/0'/0/0"
    .getWallet();
```

I think it will work, maybe?

**Comment by rhlsthrm** [comment]
Thanks @snario, we will give this a shot.

**Comment by ArjunBhuptani** [comment]
Figured it out. It was partly what @snario mentioned and partly that we were passing in the raw mnemonic into `fromMasterSeed()` instead of the raw `bip39` seed.

Fixed and deployed :ship: 

Thanks for the help, Liam!
