### ISSUE TITLE
Better Collateralization v1

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/card#4]
For the v1 mainnet release of the Card, I expect out biggest UX problems will be associated with efficient collateralization of channels.

I think there's three easy-to-implement steps we should take for now to reduce these problems (for now) while we work on better collateralization.

1) Collateralize channels on auth - right now, users have to EITHER deposit or submit one failed payment and wait 15-30 seconds for the channel to be collateralized and to send subsequent payments. Instead, we should just collateralize all channels on client authorization. This is probably less collateral efficient, but it's probably fair to assume that any user that spins up a Card will use it to send/receive payments at least once.

2) Decollateralize on burn or inactivity - Channels should automatically be decollateralized if a user burns their Card. Additionally, we should decollateralize channels automatically after a few days of inactivity. The latter is likely a little harder because it will require a unilateral close on the side of the hub (and possibly additional code on the client to handle the case where a user comes back online while the channel is being unilaterally decollateralized). Theoretically, users should not be leaving lots of funds in their Card, so it should be fine to do this.

3) UI feedback when a channel is being collateralized - I think users will be sympathetic to needing to wait a few seconds occasionally for collateralization while we work out the kinks if they're aware of whats going on. As such, it would be good to show an error or other popup on a payment that fails because of collateralization that explains what's happening and asks the user to wait 30 seconds before retrying.

So 3 changes on the card:
- [x] Request collateral on auth. We should figure out how much.
- [x] Empty withdrawal call on burn.
- [x] Dialogue when payment fails with a collateralization error that says. "Hold on! The receiver has gotten a lot of payments recently so we're recollateralizing their channel. Please try again in 30 seconds."

And then potentially 1 change in the client re: automatic unilateral response

**Comment by LayneHaber** [comment]
Automatic unilateral response may have a weird UX when logging in, the dispute path hasn't been well tested so I wouldn't include that change in the release planned for Wednesday. there are usually more issues than anticipated with dispute things :)

Request collateral also doesnt accept a user supplied "amount", instead it just relies on the hub's algo to determine it based on recent payments received, or a set collateral minimum. Would suggest setting this at ~$5 for now, since each payment received will trigger the recollateralization process

**Comment by ArjunBhuptani** [comment]
I'm ok with leaving unilateral off.

$5 seems low. Shouldn't it be equal to the amount deposited? Seems more likely that users depositing a lot will use the app more.

There's obviously a balance here b/w having more collateral in the system vs recollateralizing more often (and paying gas for it). IMO it probably makes sense to err on the side of having more collateral in the system for now because of better UX and fixed/predictable cost.

**Comment by rhlsthrm** [comment]
But "the amount deposited" will be 0 when we are collateralizing on auth, right?

This is the current calculation method:
```
/**
 * Returns two numbers `minAmount` and `maxAmount`. If the hub's BOOTY
 * balance falls under the `minAmount`, then it should be brought up to
 * `maxAmount` to ensure there is sufficient collateral.
 */
public async calculateCollateralizationTargets(state: ChannelStateBigNumber) {
  const numTippers = await this.channelsDao.getRecentTippers(state.user)
  const baseTarget = Big(numTippers).times(this.config.threadBeiLimit)
  const baseMin = numTippers > 0 ?
    this.config.beiMinCollateralization :
    toWeiBigNum(10)

  return {
    minAmount: BigNumber.max(baseMin, baseTarget).times(0.5),

    maxAmount: BigNumber.min(
      this.config.beiMaxCollateralization,

      BigNumber.max(
        baseMin,
        baseTarget.times(2.5),
      ),
    ),

    hasRecentPayments: numTippers > 0,
  }
}
```

In the auth case, there will be 0 recent "tippers", so `maxAmount` will be set to $10 initially, which seems reasonable.

**Comment by LayneHaber** [comment]
The amount people deposit is not necessarily the amount of their payments, so I think we can stick with a floor instead of matching deposits

V2 we should allow the hub to complete the payments by depositing directly into the users side of the channel and recollateralizing simultaneously. Then we can show payments as processing instead of failed.

**Comment by ArjunBhuptani** [comment]
I don't think depositing into users side would work for threads correct? It is a good idea though (for online payments).

Also, made these changes and deployed. Closing.
