### ISSUE TITLE
Snackbars: Better UI feedback

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/card#7]
There are several instances where users have reported difficulties with knowing what's going on because of a lack of visual feedback when performing actions.

We should integrate MaterialUI snackbars for the following:
- [x] Pending deposits
- [x] Deposit confirmations
- [ ] Deposit errors
- [x] Send confirmation
- [ ] Send error
- [x] Pending Withdraw
- [x] Withdraw confirmation
- [ ] Withdraw errors
- [x] "Copied!" when copying text

**Comment by hthillman** [comment]
Also snackbar for collateral error. Link: #4
